#! /bin/sh
### BEGIN INIT INFO
# Provides:          systemd-networkd-wait
# Required-Start:    $syslog $remote_fs
# Required-Stop:     $syslog $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

case "$1" in
  start)
    setsid /usr/lib/systemd/systemd-networkd-wait > /dev/null 2>&1 &
    ;;
esac
