#! /bin/sh
### BEGIN INIT INFO
# Provides:	dbus-sync
# Required-Start:	$syslog $remote_fs
# Required-Stop:	$syslog $remote_fs
# Default-Start:	2 3 4 5
# Default-Stop:	0 1 6
# Short-Description:	D-Bus sync daemon
# Description:	Ensures communication between applications via D-Bus
#		is synchronized and uninterrupted
### END INIT INFO

NAME=dbus-sync
DAEMON=/usr/bin/$NAME
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

do_start()
{
	start-stop-daemon --start --quiet --background \
		--exec $DAEMON \
		|| return 2
}

do_stop()
{
	start-stop-daemon --stop --quiet --test \
		--retry=TERM/30/KILL/5 \
		--name $NAME \
		|| return 2

	start-stop-daemon --stop --quiet --test \
		--retry=TERM/30/KILL/5 \
		--exec $DAEMON \
		|| return 2
}
case "$1" in
  start)
	do_start
	;;
  stop)
	do_stop
	;;
  restart)
	do_stop
	do_start
	;;
esac
